export const CART_TYPES = {
  ADD_PRODUCT: "ADD_PRODUCT",
  CLEAR_CART: "CLEAR_CART",
  DECREASE_QTY: "DECREASE_QTY",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};

export const AUTH_TYPES = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
};
